title: PINTS Hub
description: Pipelines for Non-Target Screening
theme: just-the-docs

url: https://EMCMS.github.io/PINTS

aux_links:
  Template Repository: https://github.com/EMCMS/PINTS

# Custom logo HTML to include an image alongside the site title
# In _config.yml
logo : "/assets/images/logo.png"