title: Just the Docs Template
description: A starter template for a Jeykll site using the Just the Docs theme!
theme: just-the-docs

url: https://EMCMS.github.io/PINTS

aux_links:
  Template Repository: https://github.com/EMCMS/PINTS

# Custom logo HTML to include an image alongside the site title
# In _config.yml
logo : "<img src='/assets/images/Logo.png' alt='Logo' style='height: 40px; margin-right: 10px;'/>"